### PR TITLE
Added slides from talks; minor editing and clean-up of index.html

### PR DESCRIPTION
**Pull request by remocollet**

### CODE REVIEW

**Comment by astro-alexis** [comment]
Hi Remo!

I am now in holidays and my work computer in Uppsala is dead.

I expect to have the possibility to push this change on our website 
sometimes second half of next week, when I am back and replaced my hard 
drives.

Would that be OK?

/alexis

**Comment by remocollet** [comment]
Hi Alexis,

Thank you for the reply. Sure, we can wait for when you come back! Enjoy your holidays!!

Remo

**Comment by astro-alexis** [comment]
The slides are now online. I had to change your comit though, the reason being:
Our webserver does not allow links to point to folders. If the folder contains a "index.html" file, it will display this page, otherwise, it will display an Error 404. In your case, the link to the slides linked to the "slides/" directory containing all PDF files. So there was an error 404 display.
Instead, I point the link to a "slides.html" page with links to individual PDF files for download: 
http://coolstars19.com/splinters/stellar-var/slides.html

/alexis

**Comment by remocollet** [comment]
Hi Alexis,

I just noticed that you elegantly solved the problem by adding a link to a separate HTML file: thank you for doing that! Apologies for not having done that myself, I wasn’t sure your web server would allow my cheap solution—in retrospect, it should have been obvious, given most professional sites wouldn’t allow a direct link to a plain folder.

Anyway, thanks again for the fixes!

Cheers,

Remo

**Comment by astro-alexis** [comment]
no problems!

/alexis

**Pull request merged**
